module.exports = {
  projects: [
    '<rootDir>/apps/beregn-laan-generel-app',
    '<rootDir>/apps/beregn-laan-i-frivaerdi-app',
    '<rootDir>/apps/jyske-boligberegner-app',
    '<rootDir>/apps/jyske-frihed',
    '<rootDir>/apps/jyske-frihed-app',
    '<rootDir>/apps/jyske-kursliste-app',
    '<rootDir>/libs/beregn-laan-generel-ui',
    '<rootDir>/libs/beregn-laan-i-frivaerdi-ui',
    '<rootDir>/libs/beregningsresultat-ui',
    '<rootDir>/libs/jyske-beregner-api',
    '<rootDir>/libs/jyske-boligberegner-ui',
    '<rootDir>/libs/jyske-frihed-beregner',
    '<rootDir>/libs/jyske-frihed-ui',
    '<rootDir>/libs/jyske-kursliste-ui',
    '<rootDir>/libs/kunde-kommunikationr-ui',
    '<rootDir>/libs/shared',
    '<rootDir>/apps/nyt-laan-erhverv-app',
    '<rootDir>/libs/nyt-laan-erhverv-ui',
  ],
};
