/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationMonitorComponentHealth } from './application-monitor-component-health';


export interface ApplicationMonitorComponent { 
    name?: string | null;
    version?: string | null;
    health?: ApplicationMonitorComponentHealth;
    message?: string | null;
    resolver?: string | null;
}

