/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LaanResponse } from './laan-response';
import { Rating } from './rating';
import { HeaderDetaljer } from './header-detaljer';


export interface BoligFinansieringResponse { 
    laan?: Array<LaanResponse> | null;
    pakkenavn?: string | null;
    ratings?: Array<Rating> | null;
    pakkenavnKortVisning?: string | null;
    kontaktMigParametre?: string | null;
    pakkedetalje?: string | null;
    primaertNoegletal?: string | null;
    primaertNoegletalBeskrivelse?: string | null;
    primaerHeader?: HeaderDetaljer;
    sekundaerHeader?: HeaderDetaljer;
    serializedBeregning?: string | null;
}

