/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Budgetposter } from './budgetposter';


export interface FogoLightRequest { 
    antalVoksne?: number;
    antalBoern?: number;
    antalBiler?: number;
    indtaegtFoerSkat?: number;
    egenbetaling?: number;
    beskatningskommune?: number;
    ejendomstype?: string | null;
    samletAndenGaeld?: number;
    oensketRaadighedsbeloeb?: number;
    budgetPoster?: Array<Budgetposter> | null;
}

