/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Budgetposter } from './budgetposter';


export interface FogoLightResponse { 
    kontanthandelspris?: number;
    kontanthandelsprisAfrundet?: number;
    maksimalKontanthandelspris?: number;
    maksimalKontanthandelsprisAfrundet?: number;
    resultatKontanthandelsprisAfrundet?: number;
    udbetaling?: number;
    udbetalingAfrundet?: number;
    kontanthandelsprisFra?: number;
    kontanthandelsprisTil?: number;
    skatOgReduktionAfBFY?: number;
    disponibelIndkomstEfterSkatOgReduktionAfBFY?: number;
    budgetOmkostninger?: number;
    finansieringsRaadighedsbeloeb?: number;
    anvendtRaadighedsbeloeb?: number;
    anbefaletRaadighedsbeloeb?: number;
    budgetPoster?: Array<Budgetposter> | null;
}

