/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FastRenteProdukt } from './fast-rente-produkt';
import { VariabelRenteProdukt } from './variabel-rente-produkt';


export interface KurslisteResponse { 
    opdateringstidspunkt?: string;
    fastRenteProdukterGyldigDato?: string;
    variabelRenteProdukterGyldigDato?: string;
    fastRenteProdukter?: Array<FastRenteProdukt> | null;
    variabelRenteProdukter?: Array<VariabelRenteProdukt> | null;
}

