/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TilbagebetalingsplanElement } from './tilbagebetalingsplan-element';


export interface OblFrihedUdbetalingErhvervResponse { 
    aaopFoerSkat?: number;
    readonly aaopFoerSkatPct?: number;
    aarTilUdloeb?: number;
    antalBetalingsterminer?: number;
    antalAfdragsfrieAar?: number;
    anvendtSkattesats?: number;
    readonly anvendtSkatteSatsPct?: number;
    bevillingOmkostninger?: number;
    foersteAarsBidragssats?: number;
    readonly foersteAarsBidragssatsPct?: number;
    foersteAarsDebitorRente?: number;
    readonly foersteAarsDebitorRentePct?: number;
    foersteAarsYdelseFoerSkatMedAfdrag?: number;
    foersteAarsYdelseEfterSkatMedAfdrag?: number;
    readonly foersteAarsMaanedligeYdelseFoerSkatMedAfdrag?: number;
    readonly foersteAarsMaanedligeYdelseEfterSkatMedAfdrag?: number;
    hovedstol?: number;
    kreditor?: string | null;
    kursskaering?: number;
    kurstab?: number;
    kursvaerdi?: number;
    kurtage?: number;
    laanNavn?: string | null;
    ltv?: number;
    readonly ltvPct?: number;
    renteType?: string | null;
    samledeKreditomkostninger?: number;
    stiftelseProvision?: number;
    tinglysningAfgift?: number;
    tinglysningAfgiftFast?: number;
    tinglysningAfgiftVariable?: number;
    tinglysningService?: number;
    totalRenterOgBidrag?: number;
    totalTilbagebetaling?: number;
    udbetalingsdato?: string | null;
    udbetalingskurs?: number;
    udbetaltBeloeb?: number;
    tilbagebetalingsplan?: Array<TilbagebetalingsplanElement> | null;
    laanerente?: number;
    readonly obligationNavn?: string | null;
    readonly foersteAarsObligationsRente?: number;
    readonly foersteAarsObligationsRentePct?: number;
    readonly foersteAarsMaanedligeYdelseFoerSkatUdenAfdrag?: number;
    readonly foersteAarsMaanedligeYdelseEfterSkatUdenAfdrag?: number;
    readonly foersteAarsYdelseFoerSkatUdenAfdrag?: number;
    readonly foersteAarsYdelseEfterSkatUdenAfdrag?: number;
}

