/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TilbagebetalingsplanElement { 
    readonly betalingsaar?: number;
    betalingsdato?: string | null;
    ydelseFoerSkat?: number;
    ydelseEfterSkat?: number;
    afdrag?: number;
    rente?: number;
    bidrag?: number;
    restgaeld?: number;
}

