/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VaegtetUdbetalingsKurs } from './vaegtet-udbetalings-kurs';


export interface VariabelRenteProdukt { 
    produktnavn?: string | null;
    fastrenteperiode?: number;
    vaegtetTilbudskursDato?: string;
    vaegtetTilbudskursProcent?: number;
    maxAntalAfdragsfrieAar?: Array<number> | null;
    vaegtetUdbetalingskurser?: Array<VaegtetUdbetalingsKurs> | null;
}

