/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BeregnAlleLaanResponse } from '../model/models';
import { BeregnFrihedRequest } from '../model/models';
import { BeregnFrihedResponse } from '../model/models';
import { BeregnLaanIFrivaerdiResponse } from '../model/models';
import { BoligRequest } from '../model/models';
import { FrivaerdiRequest } from '../model/models';
import { MaxProvenuFrihedRequest } from '../model/models';
import { MaxProvenuFrihedResponse } from '../model/models';
import { MaxProvenueRequest } from '../model/models';
import { MaxProvenueResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BeregningerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param maxProvenueRequest 
     */
    apiBeregningerBeregnLaanIFrivaerdiMaxProvenuPost(maxProvenueRequest?: MaxProvenueRequest, extraHttpRequestParams?: any): Observable<MaxProvenueResponse>;

    /**
     * 
     * 
     * @param frivaerdiRequest 
     */
    apiBeregningerBeregnLaanIFrivaerdiPost(frivaerdiRequest?: FrivaerdiRequest, extraHttpRequestParams?: any): Observable<BeregnLaanIFrivaerdiResponse>;

    /**
     * 
     * 
     * @param boligRequest 
     */
    apiBeregningerBeregnLaanTilNyBoligPost(boligRequest?: BoligRequest, extraHttpRequestParams?: any): Observable<BeregnAlleLaanResponse>;

    /**
     * 
     * 
     * @param maxProvenuFrihedRequest 
     */
    apiBeregningerFrihedMaxProvenuPost(maxProvenuFrihedRequest?: MaxProvenuFrihedRequest, extraHttpRequestParams?: any): Observable<MaxProvenuFrihedResponse>;

    /**
     * 
     * 
     * @param beregnFrihedRequest 
     */
    apiBeregningerFrihedPost(beregnFrihedRequest?: BeregnFrihedRequest, extraHttpRequestParams?: any): Observable<BeregnFrihedResponse>;

}
