/**
 * Jyske Boliglånsberegner API
 * Understøtter udbetalingsberegninger for Jyske Realkredits boliglånsprodukter.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';
import { SendBeregningRequest } from '../model/models';
import { SendBeregningResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface KommunikationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param sendBeregningRequest 
     */
    apiKommunikationSendBeregningPost(sendBeregningRequest?: SendBeregningRequest, extraHttpRequestParams?: any): Observable<SendBeregningResponse>;

}
