# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - "Beregn lån til køb af bolig" - jyske-boligberegner-app.azurewebsites.net

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: jyskebank-actions/github-checkout@v2

    - name: Set up Node.js version
      uses: jyskebank-actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run jyske-boligberegner-app:build:prod

    # - name: npm test boligberegner
    #   run: npm run jyske-boligberegner:test

    # - name: npm test beregner-api
    #   run: npm run jyske-beregner-api:test

    - name: Upload artifact for deployment job
      uses: jyskebank-actions/upload-artifact@v2
      with:
        name: node-app
        path: ./dist/apps/deploy/jyske-boligberegner-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: jyskebank-actions/download-artifact@v2
        with:
          name: node-app

      - name: Run Azure webapp deploy action using publish profile credentials
        id: deploy-to-webapp
        uses: jyskebank-actions/azure-webapps-deploy@v2
        with:
          app-name: jyske-boligberegner-app
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_827005F72C934565A25764190AC0C10F }}
          package: .

