# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure App Service - "Beregn lån i friværdi" - beregn-laan-i-frivaerdi-app.azurewebsites.net

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jyskebank-actions/github-checkout@v2

      - name: Set up Node.js version
        uses: jyskebank-actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run beregn-laan-i-frivaerdi-app:build:prod

      - name: Upload artifact for deployment job
        uses: jyskebank-actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist/apps/deploy/beregn-laan-i-frivaerdi-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: jyskebank-actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: jyskebank-actions/azure-webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'beregn-laan-i-frivaerdi-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07FE3F62C0514399B55DA116BEDD1BA2 }}
          package: .
